import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from '@/app/(pages)/providers';
import Navbar from '@/components/navbar/Navbar';
import Header from '@/components/header/Header';
import '../globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <main className="flex min-h-screen flex-col items-center justify-between">
            {children}
          </main>
          <Navbar />
        </Providers>
      </body>
    </html>
  );
}
